### ISSUE TITLE
Use Variable to Element

### ISSUE THREAD

**Issue by emresert** [gokhansisman/w3Dom-Js-Examples#1]
You can use variable to 'document.getEelement('')' line. Put this line in a variable because of EC5 semantic. It should be suitable to EC5.

**Comment by gokhansisman** [comment]
Thanks for your issue.  I solved with this code.
```
 let example =document.getElementById("myImage");
example.src =="smiley.png"; 
```

**Comment by emresert** [comment]
Congrats.  Have a good time while writing code :)

**Comment by gokhansisman** [comment]
Thank you !
